# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Ui_Calculator import Ui_CalcWindow
from Ui_Notepad import Ui_NoteWindow

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Main/img/dearth-logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget#centralwidget {background: url(:/Main/img/bg.png)}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.item1L = QtWidgets.QLabel(self.centralwidget)
        self.item1L.setGeometry(QtCore.QRect(10, 80, 76, 22))
        self.item1L.setStyleSheet("color: #ffffff;")
        self.item1L.setAlignment(QtCore.Qt.AlignCenter)
        self.item1L.setObjectName("item1L")
        self.item2L = QtWidgets.QLabel(self.centralwidget)
        self.item2L.setGeometry(QtCore.QRect(10, 190, 81, 22))
        self.item2L.setStyleSheet("color: #ffffff;")
        self.item2L.setAlignment(QtCore.Qt.AlignCenter)
        self.item2L.setObjectName("item2L")
        self.item2 = QtWidgets.QLabel(self.centralwidget)
        self.item2.setGeometry(QtCore.QRect(20, 120, 64, 64))
        self.item2.setMaximumSize(QtCore.QSize(64, 64))
        self.item2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.item2.setAutoFillBackground(False)
        self.item2.setText("")
        self.item2.setPixmap(QtGui.QPixmap(":/Main/img/calculator.png"))
        self.item2.setScaledContents(True)
        self.item2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.item2.setObjectName("item2")
        self.item1 = QtWidgets.QLabel(self.centralwidget)
        self.item1.setGeometry(QtCore.QRect(20, 10, 64, 64))
        self.item1.setMaximumSize(QtCore.QSize(64, 64))
        self.item1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.item1.setAutoFillBackground(False)
        self.item1.setText("")
        self.item1.setPixmap(QtGui.QPixmap(":/Main/img/notepad.png"))
        self.item1.setScaledContents(True)
        self.item1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.item1.setObjectName("item1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Modified
        self.item2.mousePressEvent = self.openCalculator
        self.item1.mousePressEvent = self.openNotepad

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DearthOS"))
        self.item1L.setText(_translate("MainWindow", "Notepad"))
        self.item2L.setText(_translate("MainWindow", "Calculator"))

    def openNotepad(self, Main):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_NoteWindow()
        self.ui.setupUi(self.window)
        self.ui.actionExit.triggered.connect(self.window.close)
        self.window.show()

    def openCalculator(self, Main):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_CalcWindow()
        self.ui.setupUi(self.window)
        self.window.show()

        self.window.show()
import Resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
