# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\James\Projects\DearthOS\Browser.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtWebEngineWidgets import *


class Ui_BrowserWindow(object):
    def setupUi(self, BrowserWindow):
        self.BrowserWindow = BrowserWindow
        BrowserWindow.setObjectName("BrowserWindow")
        BrowserWindow.resize(800, 600)
        BrowserWindow.setMinimumSize(QtCore.QSize(800, 600))
        BrowserWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Main/img/browser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BrowserWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(BrowserWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtUrl = QtWidgets.QLineEdit(self.centralwidget)
        self.txtUrl.setGeometry(QtCore.QRect(10, 10, 781, 20))
        self.txtUrl.setObjectName("txtUrl")
        self.frmBrowser = QtWidgets.QFrame(self.centralwidget)
        self.frmBrowser.setGeometry(QtCore.QRect(10, 40, 781, 511))
        self.frmBrowser.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmBrowser.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmBrowser.setObjectName("frmBrowser")
        BrowserWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BrowserWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        BrowserWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BrowserWindow)
        self.statusbar.setObjectName("statusbar")
        BrowserWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(BrowserWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(BrowserWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        # Modified
        self.browser = QWebEngineView()
        self.browser.setUrl(QUrl("http://www.google.com"))
        self.txtUrl.setText("http://www.google.com")
        self.browser.setGeometry(QtCore.QRect(10, 40, 781, 511))
        self.browser.setParent(self.frmBrowser)

        self.txtUrl.returnPressed.connect(self.navigate)
        self.browser.urlChanged.connect(self.updateUrl)
        self.actionAbout.triggered.connect(self.about)
        self.actionExit.triggered.connect(self.exit)
        

        self.retranslateUi(BrowserWindow)
        QtCore.QMetaObject.connectSlotsByName(BrowserWindow)

    def retranslateUi(self, BrowserWindow):
        _translate = QtCore.QCoreApplication.translate
        BrowserWindow.setWindowTitle(_translate("BrowserWindow", "Browser"))
        self.menuFile.setTitle(_translate("BrowserWindow", "File"))
        self.menuHelp.setTitle(_translate("BrowserWindow", "Help"))
        self.actionExit.setText(_translate("BrowserWindow", "Exit"))
        self.actionAbout.setText(_translate("BrowserWindow", "About"))

    def navigate(self):
        q = QUrl(self.txtUrl.text())

        if q.scheme() == "":
            q.setScheme("http")

        self.browser.setUrl(q)

    def updateUrl(self, q):
        self.txtUrl.setText(q.toString())
        self.txtUrl.setCursorPosition(0)

    def about(self, Browser):
        msg = QMessageBox()
        msg.setWindowTitle("Acerca De")
        msg.setText("Diseñado por James R. Cabrera\nProyecto SO I UJCV\n© 2023")
        msg.setIcon(QMessageBox.Information)
        x = msg.exec_()

    def exit(self, Browser):
        self.BrowserWindow.close()
import Resources_rc
