# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/james/Projects/DearthOS/Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_CalcWindow(object):
    def setupUi(self, CalcWindow):
        CalcWindow.setObjectName("CalcWindow")
        CalcWindow.resize(330, 474)
        CalcWindow.setMinimumSize(QtCore.QSize(330, 474))
        CalcWindow.setMaximumSize(QtCore.QSize(330, 474))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Main/img/calculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CalcWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(CalcWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.b7 = QtWidgets.QPushButton(self.centralwidget)
        self.b7.setGeometry(QtCore.QRect(10, 110, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.b7.setFont(font)
        self.b7.setObjectName("b7")
        self.b8 = QtWidgets.QPushButton(self.centralwidget)
        self.b8.setGeometry(QtCore.QRect(90, 110, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.b8.setFont(font)
        self.b8.setObjectName("b8")
        self.b9 = QtWidgets.QPushButton(self.centralwidget)
        self.b9.setGeometry(QtCore.QRect(170, 110, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.b9.setFont(font)
        self.b9.setObjectName("b9")
        self.b4 = QtWidgets.QPushButton(self.centralwidget)
        self.b4.setGeometry(QtCore.QRect(10, 190, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.b4.setFont(font)
        self.b4.setObjectName("b4")
        self.b5 = QtWidgets.QPushButton(self.centralwidget)
        self.b5.setGeometry(QtCore.QRect(90, 190, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.b5.setFont(font)
        self.b5.setObjectName("b5")
        self.b6 = QtWidgets.QPushButton(self.centralwidget)
        self.b6.setGeometry(QtCore.QRect(170, 190, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.b6.setFont(font)
        self.b6.setObjectName("b6")
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(10, 270, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(self.centralwidget)
        self.b2.setGeometry(QtCore.QRect(90, 270, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QPushButton(self.centralwidget)
        self.b3.setGeometry(QtCore.QRect(170, 270, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.b3.setFont(font)
        self.b3.setObjectName("b3")
        self.bDiv = QtWidgets.QPushButton(self.centralwidget)
        self.bDiv.setGeometry(QtCore.QRect(250, 110, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.bDiv.setFont(font)
        self.bDiv.setObjectName("bDiv")
        self.bMul = QtWidgets.QPushButton(self.centralwidget)
        self.bMul.setGeometry(QtCore.QRect(250, 190, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.bMul.setFont(font)
        self.bMul.setObjectName("bMul")
        self.bRes = QtWidgets.QPushButton(self.centralwidget)
        self.bRes.setGeometry(QtCore.QRect(250, 270, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.bRes.setFont(font)
        self.bRes.setObjectName("bRes")
        self.bSum = QtWidgets.QPushButton(self.centralwidget)
        self.bSum.setGeometry(QtCore.QRect(250, 350, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.bSum.setFont(font)
        self.bSum.setObjectName("bSum")
        self.b0 = QtWidgets.QPushButton(self.centralwidget)
        self.b0.setGeometry(QtCore.QRect(10, 350, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.b0.setFont(font)
        self.b0.setObjectName("b0")
        self.bIgu = QtWidgets.QPushButton(self.centralwidget)
        self.bIgu.setGeometry(QtCore.QRect(170, 350, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.bIgu.setFont(font)
        self.bIgu.setStyleSheet("background-color: #e66100;")
        self.bIgu.setObjectName("bIgu")
        self.bBor = QtWidgets.QPushButton(self.centralwidget)
        self.bBor.setGeometry(QtCore.QRect(90, 350, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.bBor.setFont(font)
        self.bBor.setObjectName("bBor")
        self.output = QtWidgets.QLineEdit(self.centralwidget)
        self.output.setEnabled(True)
        self.output.setGeometry(QtCore.QRect(10, 10, 311, 91))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.output.setFont(font)
        self.output.setObjectName("output")
        CalcWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CalcWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 330, 23))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setGeometry(QtCore.QRect(478, 310, 146, 72))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuAbout.sizePolicy().hasHeightForWidth())
        self.menuAbout.setSizePolicy(sizePolicy)
        self.menuAbout.setObjectName("menuAbout")
        CalcWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CalcWindow)
        self.statusbar.setObjectName("statusbar")
        CalcWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(CalcWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.menuAbout.triggered.connect(self.about)

        self.b0.clicked.connect(self.zero)
        self.b1.clicked.connect(self.one)
        self.b2.clicked.connect(self.two)
        self.b3.clicked.connect(self.three)
        self.b4.clicked.connect(self.four)
        self.b5.clicked.connect(self.five)
        self.b6.clicked.connect(self.six)
        self.b7.clicked.connect(self.seven)
        self.b8.clicked.connect(self.eight)
        self.b9.clicked.connect(self.nine)

        self.bSum.clicked.connect(self.plus)
        self.bRes.clicked.connect(self.minus)
        self.bMul.clicked.connect(self.times)
        self.bDiv.clicked.connect(self.divide)
        self.bBor.clicked.connect(self.erase)
        self.bIgu.clicked.connect(self.equal)

        self.retranslateUi(CalcWindow)
        QtCore.QMetaObject.connectSlotsByName(CalcWindow)

    def retranslateUi(self, CalcWindow):
        _translate = QtCore.QCoreApplication.translate
        CalcWindow.setWindowTitle(_translate("CalcWindow", "Calculator"))
        self.b7.setText(_translate("CalcWindow", "7"))
        self.b8.setText(_translate("CalcWindow", "8"))
        self.b9.setText(_translate("CalcWindow", "9"))
        self.b4.setText(_translate("CalcWindow", "4"))
        self.b5.setText(_translate("CalcWindow", "5"))
        self.b6.setText(_translate("CalcWindow", "6"))
        self.b1.setText(_translate("CalcWindow", "1"))
        self.b2.setText(_translate("CalcWindow", "2"))
        self.b3.setText(_translate("CalcWindow", "3"))
        self.bDiv.setText(_translate("CalcWindow", "/"))
        self.bMul.setText(_translate("CalcWindow", "X"))
        self.bRes.setText(_translate("CalcWindow", "-"))
        self.bSum.setText(_translate("CalcWindow", "+"))
        self.b0.setText(_translate("CalcWindow", "0"))
        self.bIgu.setText(_translate("CalcWindow", "="))
        self.bBor.setText(_translate("CalcWindow", "⌫"))
        self.menuAbout.setTitle(_translate("CalcWindow", "About"))
        self.actionAbout.setText(_translate("CalcWindow", "About"))

    def equal(self, Calc):
        eq = self.output.text()
        try:
            self.output.setText(str(eval(eq)))
        except:
            self.output.setText("")

    def erase(self, Calc):
        prev = self.output.text()
        new = prev[:len(prev) - 1]
        self.output.setText(new)

    def plus(self, Calc):
        prev = self.output.text()
        self.output.setText(prev + "+")

    def minus(self, Calc):
        prev = self.output.text()
        self.output.setText(prev + "-")
    
    def times(self, Calc):
        prev = self.output.text()
        self.output.setText(prev + "*")

    def divide(self, Calc):
        prev = self.output.text()
        self.output.setText(prev + "/")

    def zero(self, Calc):
        prev = self.output.text()
        self.output.setText(prev + "0")

    def one(self, Calc):
        prev = self.output.text()
        self.output.setText(prev + "1")

    def two(self, Calc):
        prev = self.output.text()
        self.output.setText(prev + "2")
    
    def three(self, Calc):
        prev = self.output.text()
        self.output.setText(prev + "3")

    def four(self, Calc):
        prev = self.output.text()
        self.output.setText(prev + "4")

    def five(self, Calc):
        prev = self.output.text()
        self.output.setText(prev + "5")

    def six(self, Calc):
        prev = self.output.text()
        self.output.setText(prev + "6")

    def seven(self, Calc):
        prev = self.output.text()
        self.output.setText(prev + "7")

    def eight(self, Calc):
        prev = self.output.text()
        self.output.setText(prev + "8")

    def nine(self, Calc):
        prev = self.output.text()
        self.output.setText(prev + "9")

    def about(self, Calc):
        msg = QMessageBox()
        msg.setWindowTitle("Acerca De")
        msg.setText("Diseñado por James R. Cabrera\nProyecto SO I UJCV\n© 2023")
        msg.setIcon(QMessageBox.Information)
        x = msg.exec_()

import Resources_rc
