# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\James\Projects\DearthOS\DocumentViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtWebEngineWidgets import *


class Ui_DocumentViewerWindow(object):
    def setupUi(self, DocumentViewerWindow):
        self.DocumentViewerWindow = DocumentViewerWindow
        DocumentViewerWindow.setObjectName("DocumentViewerWindow")
        DocumentViewerWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DocumentViewerWindow.sizePolicy().hasHeightForWidth())
        DocumentViewerWindow.setSizePolicy(sizePolicy)
        DocumentViewerWindow.setMinimumSize(QtCore.QSize(800, 600))
        DocumentViewerWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Main/img/document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DocumentViewerWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(DocumentViewerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frmBrowser = QtWidgets.QFrame(self.centralwidget)
        self.frmBrowser.setGeometry(QtCore.QRect(10, 10, 781, 541))
        self.frmBrowser.setStyleSheet("color: rgb(0, 0, 0);")
        self.frmBrowser.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmBrowser.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmBrowser.setObjectName("frmBrowser")
        DocumentViewerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DocumentViewerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        DocumentViewerWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DocumentViewerWindow)
        self.statusbar.setObjectName("statusbar")
        DocumentViewerWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(DocumentViewerWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpen = QtWidgets.QAction(DocumentViewerWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(DocumentViewerWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        # Modified
        self.browser = QWebEngineView()
        self.browser.settings().setAttribute(QWebEngineSettings.PluginsEnabled, True)
        self.browser.settings().setAttribute(QWebEngineSettings.PdfViewerEnabled, True)
        self.browser.setGeometry(QtCore.QRect(10, 10, 781, 541))
        self.browser.setParent(self.frmBrowser)

        self.actionOpen.triggered.connect(self.openFile)
        self.actionExit.triggered.connect(self.exit)
        self.actionAbout.triggered.connect(self.about)

        self.retranslateUi(DocumentViewerWindow)
        QtCore.QMetaObject.connectSlotsByName(DocumentViewerWindow)

    def retranslateUi(self, DocumentViewerWindow):
        _translate = QtCore.QCoreApplication.translate
        DocumentViewerWindow.setWindowTitle(_translate("DocumentViewerWindow", "Document Viewer"))
        self.menuFile.setTitle(_translate("DocumentViewerWindow", "File"))
        self.menuHelp.setTitle(_translate("DocumentViewerWindow", "Help"))
        self.actionAbout.setText(_translate("DocumentViewerWindow", "About"))
        self.actionOpen.setText(_translate("DocumentViewerWindow", "Open"))
        self.actionExit.setText(_translate("DocumentViewerWindow", "Exit"))

    def openFile(self, IV):
        filename = QtWidgets.QFileDialog.getOpenFileName()

        q = QUrl(filename[0])

        if q.scheme() == "":
            q.setScheme("http")

        self.browser.setUrl(q)


    def about(self, IV):
        msg = QMessageBox()
        msg.setWindowTitle("Acerca De")
        msg.setText("Diseñado por James R. Cabrera\nProyecto SO I UJCV\n© 2023")
        msg.setIcon(QMessageBox.Information)
        x = msg.exec_()

    def exit(self, IV):
        self.DocumentViewerWindow.close()
import Resources_rc
