# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/james/Projects/DearthOS/ImageViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QMessageBox


class Ui_ImageViewerWindow(object):
    def setupUi(self, ImageViewerWindow):
        self.ImageViwerWindow = ImageViewerWindow
        ImageViewerWindow.setObjectName("ImageViewerWindow")
        ImageViewerWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ImageViewerWindow.sizePolicy().hasHeightForWidth())
        ImageViewerWindow.setSizePolicy(sizePolicy)
        ImageViewerWindow.setMinimumSize(QtCore.QSize(800, 600))
        ImageViewerWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Main/img/image-viewer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ImageViewerWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(ImageViewerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 781, 531))
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        ImageViewerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ImageViewerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 34))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        ImageViewerWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ImageViewerWindow)
        self.statusbar.setObjectName("statusbar")
        ImageViewerWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(ImageViewerWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpen = QtWidgets.QAction(ImageViewerWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(ImageViewerWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        # Modified
        self.actionOpen.triggered.connect(self.openFile)
        self.actionExit.triggered.connect(self.exit)
        self.actionAbout.triggered.connect(self.about)

        self.retranslateUi(ImageViewerWindow)
        QtCore.QMetaObject.connectSlotsByName(ImageViewerWindow)

    def retranslateUi(self, ImageViewerWindow):
        _translate = QtCore.QCoreApplication.translate
        ImageViewerWindow.setWindowTitle(_translate("ImageViewerWindow", "Image Viewer"))
        self.menuFile.setTitle(_translate("ImageViewerWindow", "File"))
        self.menuHelp.setTitle(_translate("ImageViewerWindow", "Help"))
        self.actionAbout.setText(_translate("ImageViewerWindow", "About"))
        self.actionOpen.setText(_translate("ImageViewerWindow", "Open"))
        self.actionExit.setText(_translate("ImageViewerWindow", "Exit"))

    def openFile(self, IV):
        filename = QtWidgets.QFileDialog.getOpenFileName()
        image = QImage(filename[0])
        self.label.setPixmap(QPixmap.fromImage(image))

    def about(self, IV):
        msg = QMessageBox()
        msg.setWindowTitle("Acerca De")
        msg.setText("Diseñado por James R. Cabrera\nProyecto SO I UJCV\n© 2023")
        msg.setIcon(QMessageBox.Information)
        x = msg.exec_()

    def exit(self, IV):
        self.ImageViwerWindow.close()

import Resources_rc
