# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Main import Ui_MainWindow
from PyQt5.QtWidgets import QMessageBox

class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginWindow.sizePolicy().hasHeightForWidth())
        LoginWindow.setSizePolicy(sizePolicy)
        LoginWindow.setMinimumSize(QtCore.QSize(800, 600))
        LoginWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Main/img/dearth-logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(260, 20, 291, 261))
        self.logo.setAutoFillBackground(False)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/Main/img/dearth-logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.lblUser = QtWidgets.QLabel(self.centralwidget)
        self.lblUser.setGeometry(QtCore.QRect(190, 290, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.lblUser.setFont(font)
        self.lblUser.setObjectName("lblUser")
        self.lblPass = QtWidgets.QLabel(self.centralwidget)
        self.lblPass.setGeometry(QtCore.QRect(80, 370, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.lblPass.setFont(font)
        self.lblPass.setObjectName("lblPass")
        self.txtUser = QtWidgets.QLineEdit(self.centralwidget)
        self.txtUser.setGeometry(QtCore.QRect(310, 300, 391, 51))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.txtUser.setFont(font)
        self.txtUser.setObjectName("txtUser")
        self.txtPass = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPass.setGeometry(QtCore.QRect(310, 380, 391, 51))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.txtPass.setFont(font)
        self.txtPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPass.setObjectName("txtPass")
        self.btnLogin = QtWidgets.QPushButton(self.centralwidget)
        self.btnLogin.setGeometry(QtCore.QRect(280, 470, 271, 81))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.btnLogin.setFont(font)
        self.btnLogin.setFlat(False)
        self.btnLogin.setObjectName("btnLogin")
        LoginWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.btnLogin.clicked.connect(self.login)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "DearthOS Login"))
        self.lblUser.setText(_translate("LoginWindow", "User:"))
        self.lblPass.setText(_translate("LoginWindow", "Password:"))
        self.btnLogin.setText(_translate("LoginWindow", "Login"))

    def login(self, Login):
        if self.txtUser.text() == "Salieri" and self.txtPass.text() == "Sonata":
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_MainWindow()
            self.ui.setupUi(self.window)
            self.window.show()
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Login failed")
            msg.setText("Username/Password incorrect!")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec_()

        self.txtUser.setText("")
        self.txtPass.setText("")
import Resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
