# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/james/Projects/DearthOS/MusicPlayer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtCore import QUrl
from PyQt5.QtMultimedia import QMediaPlayer, QMediaContent


class Ui_MusicWindow(object):
    def setupUi(self, MusicWindow):
        MusicWindow.setObjectName("MusicWindow")
        MusicWindow.resize(350, 155)
        MusicWindow.setMinimumSize(QtCore.QSize(350, 155))
        MusicWindow.setMaximumSize(QtCore.QSize(350, 155))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Main/img/music.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MusicWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MusicWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnPlay = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlay.setGeometry(QtCore.QRect(10, 50, 331, 38))
        self.btnPlay.setObjectName("btnPlay")
        self.btnFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnFile.setGeometry(QtCore.QRect(10, 10, 107, 38))
        self.btnFile.setObjectName("btnFile")
        self.btnVolUp = QtWidgets.QPushButton(self.centralwidget)
        self.btnVolUp.setGeometry(QtCore.QRect(120, 10, 107, 38))
        self.btnVolUp.setObjectName("btnVolUp")
        self.btnVolDown = QtWidgets.QPushButton(self.centralwidget)
        self.btnVolDown.setGeometry(QtCore.QRect(230, 10, 111, 38))
        self.btnVolDown.setObjectName("btnVolDown")
        MusicWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MusicWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 34))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MusicWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MusicWindow)
        self.statusbar.setObjectName("statusbar")
        MusicWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MusicWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        #Modified
        self.player = QMediaPlayer()
        self.file = ""

        self.btnFile.clicked.connect(self.selectFile)
        self.btnPlay.clicked.connect(self.play)
        self.btnVolUp.clicked.connect(self.volumeUp)
        self.btnVolDown.clicked.connect(self.volumeDown)
        self.actionAbout.triggered.connect(self.about)


        self.retranslateUi(MusicWindow)
        QtCore.QMetaObject.connectSlotsByName(MusicWindow)

    def retranslateUi(self, MusicWindow):
        _translate = QtCore.QCoreApplication.translate
        MusicWindow.setWindowTitle(_translate("MusicWindow", "MainWindow"))
        self.btnPlay.setText(_translate("MusicWindow", "Play"))
        self.btnFile.setText(_translate("MusicWindow", "File"))
        self.btnVolUp.setText(_translate("MusicWindow", "+"))
        self.btnVolDown.setText(_translate("MusicWindow", "-"))
        self.menuHelp.setTitle(_translate("MusicWindow", "Help"))
        self.actionAbout.setText(_translate("MusicWindow", "About"))

    def about(self, Music):
        msg = QMessageBox()
        msg.setWindowTitle("Acerca De")
        msg.setText("Diseñado por James R. Cabrera\nProyecto SO I UJCV\n© 2023")
        msg.setIcon(QMessageBox.Information)
        x = msg.exec_()

    def volumeUp(self, Music):
        currentVolume = self.player.volume()
        self.player.setVolume(currentVolume + 5)

    def volumeDown(self, Music):
        currentVolume = self.player.volume()
        self.player.setVolume(currentVolume - 5)

    def volumeMute(self, Music):
        self.player.setMuted(not self.player.isMuted())

    def selectFile(self, Music):
        filename = QtWidgets.QFileDialog.getOpenFileName()
        self.file = filename[0]

    def play(self, Music):
        url = QUrl.fromLocalFile(self.file)
        content = QMediaContent(url)

        self.player.setMedia(content)
        self.player.play()
        

import Resources_rc
